-- Required application defaults. Safe to repeat; does not overwrite business settings.
BEGIN;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('dashboard.view', 'dashboard', 'view', 'View dashboard') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('leads.view', 'leads', 'view', 'View leads') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('customers.view', 'customers', 'view', 'View customers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('appointments.view', 'appointments', 'view', 'View appointments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('calendar.view', 'calendar', 'view', 'View calendar') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('campaigns.view', 'campaigns', 'view', 'View campaigns') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('offers.view', 'offers', 'view', 'View offers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('coupons.view', 'coupons', 'view', 'View coupons') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('referrals.view', 'referrals', 'view', 'View referrals') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('reviews.view', 'reviews', 'view', 'View reviews') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('testimonials.view', 'testimonials', 'view', 'View testimonials') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('gallery.view', 'gallery', 'view', 'View gallery') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('services.view', 'services', 'view', 'View services') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('products.view', 'products', 'view', 'View products') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('pages.view', 'pages', 'view', 'View pages') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('faqs.view', 'faqs', 'view', 'View faqs') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('media.view', 'media', 'view', 'View media') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('seo.view', 'seo', 'view', 'View seo') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('analytics.view', 'analytics', 'view', 'View analytics') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('trafficSources.view', 'trafficSources', 'view', 'View trafficSources') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('reports.view', 'reports', 'view', 'View reports') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('businessProfile.view', 'businessProfile', 'view', 'View businessProfile') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('serviceAreas.view', 'serviceAreas', 'view', 'View serviceAreas') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('businessHours.view', 'businessHours', 'view', 'View businessHours') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('staff.view', 'staff', 'view', 'View staff') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('roles.view', 'roles', 'view', 'View roles') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('activityLogs.view', 'activityLogs', 'view', 'View activityLogs') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('settings.view', 'settings', 'view', 'View settings') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('forms.view', 'forms', 'view', 'View forms') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('followUps.view', 'followUps', 'view', 'View followUps') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('leadSources.view', 'leadSources', 'view', 'View leadSources') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('notifications.view', 'notifications', 'view', 'View notifications') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('leads.create', 'leads', 'create', 'Create leads') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('leads.update', 'leads', 'update', 'Update leads and status') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('leads.delete', 'leads', 'delete', 'Delete leads') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('customers.create', 'customers', 'create', 'Create customers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('customers.update', 'customers', 'update', 'Update customers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('customers.delete', 'customers', 'delete', 'Delete customers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('appointments.create', 'appointments', 'create', 'Create appointments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('appointments.update', 'appointments', 'update', 'Update appointments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('appointments.cancel', 'appointments', 'cancel', 'Cancel appointments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('services.manage', 'services', 'manage', 'Manage services') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('staff.create', 'staff', 'create', 'Create team members') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('staff.update', 'staff', 'update', 'Update team members') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('staff.deactivate', 'staff', 'deactivate', 'Deactivate team members') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('staff.reset_password', 'staff', 'reset_password', 'Reset a member password') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('roles.manage_overrides', 'roles', 'manage_overrides', 'Manage member permission overrides') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('businessProfile.update', 'businessProfile', 'update', 'Update business profile') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('businessHours.update', 'businessHours', 'update', 'Update business hours') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('serviceAreas.update', 'serviceAreas', 'update', 'Update service areas') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('settings.update', 'settings', 'update', 'Update business settings') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('appointments.delete', 'appointments', 'delete', 'Delete appointments') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('reports.export', 'reports', 'export', 'Export reports as CSV') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('faqs.manage', 'faqs', 'manage', 'Create, update and delete FAQs') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('testimonials.manage', 'testimonials', 'manage', 'Create, update and delete testimonials') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('media.manage', 'media', 'manage', 'Create, update and delete media items') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('gallery.manage', 'gallery', 'manage', 'Create, update and delete gallery images') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('offers.manage', 'offers', 'manage', 'Create, update and delete offers') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('coupons.manage', 'coupons', 'manage', 'Create, update and delete coupons') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('reviews.manage', 'reviews', 'manage', 'Create, approve, reject and delete reviews') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('forms.manage', 'forms', 'manage', 'Create, update and delete custom forms') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('pages.manage', 'pages', 'manage', 'Create, update and delete website pages/content blocks') ON CONFLICT DO NOTHING;
INSERT INTO public.permissions(permission_key,feature_key,action,description) VALUES ('seo.manage', 'seo', 'manage', 'Update SEO settings and tracking codes') ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','dashboard.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','leads.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','customers.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','appointments.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','calendar.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','campaigns.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','offers.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','coupons.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','referrals.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','reviews.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','testimonials.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','gallery.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','services.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','products.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','pages.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','faqs.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','media.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','seo.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','analytics.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','trafficSources.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','reports.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','businessProfile.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','serviceAreas.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','businessHours.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','staff.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','roles.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','activityLogs.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','settings.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','forms.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','followUps.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','leadSources.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','notifications.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','leads.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','leads.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','leads.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','customers.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','customers.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','customers.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','appointments.cancel',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','staff.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','staff.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','staff.deactivate',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','staff.reset_password',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','roles.manage_overrides',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','businessProfile.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','businessHours.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','serviceAreas.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','settings.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','dashboard.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','leads.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','customers.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','appointments.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','calendar.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','services.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','analytics.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','reports.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','forms.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','followUps.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','leadSources.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','notifications.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','leads.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','leads.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','leads.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','customers.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','customers.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','customers.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','appointments.cancel',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','dashboard.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','leads.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','customers.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','appointments.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','calendar.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','services.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','analytics.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','reports.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','followUps.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','notifications.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','leads.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','customers.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('supervisor','appointments.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','dashboard.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','leads.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','customers.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','appointments.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','calendar.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','services.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','notifications.view',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','leads.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','leads.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','customers.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('superadmin','services.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','services.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','services.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','services.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','appointments.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','appointments.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','appointments.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','appointments.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','appointments.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','appointments.delete',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','appointments.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','appointments.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','appointments.create',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('staff','appointments.update',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','reports.export',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','reports.export',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','reports.export',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','faqs.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','faqs.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','faqs.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','testimonials.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','testimonials.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','testimonials.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','media.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','media.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','media.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','gallery.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','gallery.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','gallery.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','offers.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','offers.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','offers.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','coupons.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','coupons.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','coupons.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','reviews.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','reviews.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','reviews.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','forms.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','forms.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','forms.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','pages.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','pages.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','pages.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('owner','seo.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('admin','seo.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.role_permissions(role,permission_key,allowed) VALUES ('manager','seo.manage',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('forms',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('leads',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('dashboard',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('businessProfile',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('appointments',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('offers',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('pages',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('media',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('seo',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('followUps',false) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('calendar',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('settings',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('staff',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('campaigns',false) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('testimonials',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('leadSources',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('reports',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('faqs',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('services',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('referrals',false) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('reviews',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('businessHours',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('gallery',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('roles',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('coupons',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('customers',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('serviceAreas',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('products',false) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('notifications',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('activityLogs',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('trafficSources',true) ON CONFLICT DO NOTHING;
INSERT INTO public.feature_settings(feature_key,enabled) VALUES ('analytics',true) ON CONFLICT DO NOTHING;
INSERT INTO public.communication_settings(id,contact_mode,emails_enabled) VALUES(true,'phone',false) ON CONFLICT DO NOTHING;
INSERT INTO public.business_settings(business_name,timezone) SELECT 'Your Business','UTC' WHERE NOT EXISTS(SELECT 1 FROM public.business_settings);
INSERT INTO public.subscriptions(plan,start_date,end_date,is_active) SELECT 'monthly',current_date,current_date+30,true WHERE NOT EXISTS(SELECT 1 FROM public.subscriptions);
INSERT INTO public.business_hours(day_of_week,day_name,is_closed,is_24h) SELECT n,(ARRAY['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])[n+1],true,false FROM generate_series(0,6) n ON CONFLICT DO NOTHING;
COMMIT;
